### PR TITLE
Use xterm cuz more linux distro has it

### PR DESCRIPTION
**Pull request by borosmatefoszk**
Use xterm cuz more linux distro has it

### CODE REVIEW

**Comment by Michal2SAB** [comment]
Any way I can confirm it's true? I tried it on mine just now and the xterm command doesn't exist

**Comment by borosmatefoszk** [comment]
kali use xterm
parrotOs use xterm
blackbox os use xterm every pentesting OS have xterm too and if u doesn't have u can easily install with apt-get install xterm

**Comment by petjal** [comment]
for headless (no X needed), consider a terminal multiplexer such as screen, tmux, or byobu.  Here is my tmux command (run in /dev/shm for speed, edited to write winnings to ~/Success.txt, four concurrent sessions, one for each cpu core, timeout to kill memory leak, capped at 10000 in case I forget about this thing):
`/dev/shm/Linux$ for i in {1..10000} ; do tmux new-session -d timeout 20s nice -20 node generator.js ; sleep 5s ; done `

so, like, what if ambitious malicious actors started throwing mining-farm-level rigs at this, um, problem?  (suggests not keeping all of ones bitcoin eggs in one address basket)

**Comment by Michal2SAB** [comment]
> for headless (no X needed), consider a terminal multiplexer such as screen, tmux, or byobu. Here is my tmux command (run in /dev/shm for speed, edited to write winnings to ~/Success.txt, four concurrent sessions, one for each cpu core, timeout to kill memory leak, capped at 10000 in case I forget about this thing, nice so I can log back in): `/dev/shm/Linux$ for i in {1..10000} ; do tmux new-session -d timeout 20s nice -20 node generator.js ; sleep 5s ; done `
> 
> so, like, what if ambitious malicious actors started throwing mining-farm-level rigs at this, um, problem? (suggests not keeping all of ones bitcoin eggs in one address basket)

Screenshot_2

**Review by Michal2SAB — APPROVED** [review]
using xterm instead of gnome-terminal, apt-get install xterm if you don't have it, need to be root

**Pull request merged**
