### PR TITLE
Improved Documentation

### PR DESCRIPTION
**Pull request by OverloadedTech**
Dear community and @Michal2SAB,
I just added more information to the Bitcoin-Steal repository, so new users can start to use more easily this amazing tool
I hope my edits can be useful, and they can be merged to the original repository
Let me know what to improve and if you liked it
Have a nice day
Luca
Bolzano, Italy, 14 November 2022

### CODE REVIEW

**Review by neverm8 — APPROVED** [review]

**Comment by neverm8** [comment]
I'm trying to commit, but nuffin doin?

**Comment by OverloadedTech** [comment]
Hi,
I just added more information for new users in the docs and in the code

**Comment by OverloadedTech** [comment]
Can you merge?

**Comment by OverloadedTech** [comment]
This request is done

**Pull request closed without merging**
